version: '3'

services:
  tokenizationapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: tokenization
    container_name: tokenizationapp
    restart: always 
    ports:
      - 3010:3000
  
    environment:
      MONGODB_URL: ${MONGODB_URL}
      SECRET_KEY: ${SECRET_KEY}
    
    networks:
      - webnet    

  db:
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: tokenization
    volumes:
      - ./mongo:/data/db

    networks:
      - webnet

networks:
  webnet: